### ISSUE TITLE
First card wild does not have a color

### ISSUE THREAD

**Issue by Hexadigital** [Hexadigital/python-uno#3]
If the first card played (by the dealer) is a Wild card, then it will not have a set color.

Can be fixed by randomly assigning a color, or by preventing a wild card from being the first card. Look up how the actual rules handle it?

**Comment by swflint** [comment]
I'd suggest picking a colour at random.  I'd be surprised if the rules have anything to say about it.

**Comment by Hexadigital** [comment]
"If the first card played is a wild, the player to the left of the dealer calls out a color - then plays."

**Comment by swflint** [comment]
The rules have spoken!
