### ISSUE TITLE
Theme packs are not yet supported

### ISSUE THREAD

**Issue by Hexadigital** [Hexadigital/python-uno#5]
Players cannot specify a "theme pack" in their options, nor is the "main" story separated from the rest.

**Comment by swflint** [comment]
Store a theme in a JSON file!

**Comment by Hexadigital** [comment]
Would it not be easier to keep it in Python?

**Comment by swflint** [comment]
It could be, but doing it this way could make it a bit easier for
non-programmers to write themes for.

**Comment by Hexadigital** [comment]
I feel like it would be better to keep it in Python, and if needed (assuming a command-line UNO somehow explodes into popularity) create a GUI-based tool for creating and editing theme packs.

**Comment by swflint** [comment]
All right then.  Otherwise, I'd use classes to do it.
